# Form implementation generated from reading ui file 'd:\NTPU\110_2_Soft_Design\Code\HW\Final\Final_sub_PTT.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form.resize(694, 668)
        Form.setStyleSheet("background-color: rgb(0, 44, 47);\n"
"color: rgb(255, 255, 255);")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(20, 60, 651, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: rgb(178, 165, 159);\n"
"color: rgb(255, 255, 255);")
        self.label_title.setText("")
        self.label_title.setObjectName("label_title")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(360, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_Papertext = QtWidgets.QTextBrowser(Form)
        self.textBrowser_Papertext.setGeometry(QtCore.QRect(20, 260, 321, 391))
        self.textBrowser_Papertext.setStyleSheet("background-color: rgb(2, 52, 89);\n"
"color: rgb(255, 255, 255);")
        self.textBrowser_Papertext.setObjectName("textBrowser_Papertext")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pBut_to_main = QtWidgets.QPushButton(Form)
        self.pBut_to_main.setGeometry(QtCore.QRect(20, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pBut_to_main.setFont(font)
        self.pBut_to_main.setStyleSheet("background-color: rgb(30, 100, 110);\n"
"color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\NTPU\\110_2_Soft_Design\\Code\\HW\\Final\\../HW2/711033115_HW2/icon/arrow-left-circle.svg"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.pBut_to_main.setIcon(icon)
        self.pBut_to_main.setObjectName("pBut_to_main")
        self.label_time = QtWidgets.QLabel(Form)
        self.label_time.setGeometry(QtCore.QRect(70, 170, 261, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("background-color: rgb(2, 52, 89);\n"
"color: rgb(255, 255, 255);")
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.label_board = QtWidgets.QLabel(Form)
        self.label_board.setGeometry(QtCore.QRect(550, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_board.setFont(font)
        self.label_board.setStyleSheet("background-color: rgb(2, 52, 89);\n"
"color: rgb(255, 255, 255);")
        self.label_board.setText("")
        self.label_board.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_board.setObjectName("label_board")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(500, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.tableView_Comment = QtWidgets.QTableView(Form)
        self.tableView_Comment.setGeometry(QtCore.QRect(360, 170, 311, 481))
        self.tableView_Comment.setStyleSheet("background-color: rgb(2, 52, 89);\n"
"color: rgb(0, 0, 0);")
        self.tableView_Comment.setObjectName("tableView_Comment")
        self.label_author = QtWidgets.QLabel(Form)
        self.label_author.setGeometry(QtCore.QRect(70, 130, 261, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_author.setFont(font)
        self.label_author.setStyleSheet("background-color: rgb(2, 52, 89);\n"
"color: rgb(255, 255, 255);")
        self.label_author.setText("")
        self.label_author.setObjectName("label_author")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "作者"))
        self.label_3.setText(_translate("Form", "推文"))
        self.label_4.setText(_translate("Form", "時間"))
        self.label_5.setText(_translate("Form", "本文"))
        self.pBut_to_main.setText(_translate("Form", "  返回運動速報"))
        self.label_6.setText(_translate("Form", "看板"))
